### ISSUE TITLE
Wrong image view

### ISSUE THREAD

**Issue by ippocratis** [savvasdalkitsis/uhuruphotos-android#110]
In albums, either auto generated or user albums, when an image selected to view sometimes the first image in the album is opened instead of the selected image.

**Comment by nagarrido** [comment]
Same happens to me

**Comment by nagarrido** [comment]
Is there any update on this?

**Comment by savvasdalkitsis** [comment]
I believe this may have been fixed. Are you still seeing this?

**Comment by ippocratis** [comment]
Yes true 
seems OK now

**Comment by nagarrido** [comment]
I can also confirm I'm not having the problem anymore
