### ISSUE TITLE
Optimize app for autofill?

### ISSUE THREAD

**Issue by ippocratis** [savvasdalkitsis/uhuruphotos-android#148]
When server restarts or periodically user have to fill the librephotoss credentials. 
Autofill services that I tried (bitwarden and google) cant pic up the input field

As I read in google's documentation  

"Apps that use standard views work with the autofill framework without requiring special configuration"

So I dont know what is my case

However, you can optimize how your app works with the framework.

Source
https://developer.android.com/guide/topics/text/autofill-optimize

Thanks

**Comment by ippocratis** [comment]
V0.0.102 kinda solves this
Probably it's the  "Option to save user credentials using CredentialManager" in the changelog?
google password manager popsup and ask to save the user/password
On Next login autofill with google password manager works fine even if its not the default autofill service
3rd party password managers still don't work even if they are selected as the default autofill dervice

Thanks

**Comment by savvasdalkitsis** [comment]
The need for this (which I am not sure is even possible yet since the autofill api is a little behind when it comes to Jetpack Compose) will be partially gone once #455 is implemented so I will close this to keep the issue number managable
