### ISSUE TITLE
There was an error loading photo details

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#150]
In almost every photo I view I get the error "there was an error loading poto details" ![Screenshot_20221109_082738_Photos~2.jpg](https://user-images.githubusercontent.com/37604199/200818970-483fb5ac-117e-489f-a20f-6f64e74801c6.jpg)

I also have the logs in case they are useful

**Comment by Boxswurst** [comment]
Same here on Pixel 7 Pro.

**Comment by ippocratis** [comment]
Server side related
You need to have rwx permissions for others.on you photos directory in librephotos

**Comment by ippocratis** [comment]
I was using an old librephotos image
Updated and indeed the error messaged pops up
I can see the photo details though
