### ISSUE TITLE
All photos not loading automatically 

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#153]
Some photos only load when I manually refresh the corresponding day. Due to this, I may miss some old photos from the timeline, and of course this is not ideal. Is this expected behaviour or a bug?

**Comment by nagarrido** [comment]
Just figured out when this happens. If I go to a person's album and then back to the timeline, all the photos from a day in which the person appeared are hidden except for the photos in which the person appears. I sent the logs by email

**Comment by savvasdalkitsis** [comment]
Hm. I will try to replicate and fix, thanks :)
