### ISSUE TITLE
Wrong (?) Sync state(?) icon 

### ISSUE THREAD

**Issue by ippocratis** [savvasdalkitsis/uhuruphotos-android#162]
A cloud icon appears momentarily on the image thumbnail as long as I scroll.  
I assume to indicate its a cloud photo regardless in if the photo is in local storage or not and disapears when scrolling stop.
acording to the 0.0.80 feature drop the local photos should appear in the feed together with the cloud photos and the thumbnails will show a sync state (local,remote,synced)(icon?)

**Comment by savvasdalkitsis** [comment]
There are three icons showing in the list while you scroll (they autohide so they are not always cluttering the UI):

Local only:
<img width="175" alt="Screenshot 2023-02-02 at 12 27 30" src="https://user-images.githubusercontent.com/873077/216325374-ded2bbd1-8fbc-4d4b-aa14-5d58be0fcc1b.png">

Fully synced and remote only :
![Uploading Screenshot 2023-02-02 at 12.27.51.png…]()

Are you seeing the wrong icon for photos that you have locally and remote?

**Comment by ippocratis** [comment]
I see only the third icon

I already made a full sync if that matters

**Comment by savvasdalkitsis** [comment]
Can you see the local folders on the Library tab? I currently don't have the UI asking for Storage permissions on the main Feed tab so you will have to make sure to give the app permissions to read your local photos by going to Library and selecting the Local Photos button. Once the app can see the local photos, they should appear on the Feed.

If you can see local photos on the Library tab but not on the feed then the app may not have been able to automatically determine your default Camera folder (it's surprisingly difficult and not standard on Android). It makes a best effort attempt to find it but if it can't then it won't show in the Feed. There is a feature planned where if this happens, the app will ask you to choose one of the folders it can see as the default camera folder.

**Comment by ippocratis** [comment]
Yes already had done  that before the update
but tried again after reinstalling the app

Same only the third icon show's

One observation :
The local albums folder disappears from library after granting the permission

**Comment by savvasdalkitsis** [comment]
The button should be removed from the library once you give permission but it should be replaced with the local folders showing your photos. do you see the local photos in the Library tab?

**Comment by ippocratis** [comment]
No that is missing

**Comment by savvasdalkitsis** [comment]
It takes a while for the app to start scanning the local folders. Navigate away and come back to that screen after a while? There should also be a notification showing you the scanning progress

**Comment by savvasdalkitsis** [comment]
Any updates on this @ippocratis ? Have you managed to see the icons correctly now?

**Comment by savvasdalkitsis** [comment]
I bet it's the app not being to select the correct camera folder. Can you send me the names of your camera folders on those two devices as they appear in the Library tab? And maybe their full path which you can see by opening one of the photos in those folders and seeing the details section?

**Comment by ippocratis** [comment]
/storage/emulated/0/DCIM/

On all 3 devices

**Comment by savvasdalkitsis** [comment]
Hm is that the full path or is there a subfolder under DCIM that the camera photos are under?

**Comment by ippocratis** [comment]
the full paths for camera photos is
/storage/emulated/0/DCIM/Camera

**Comment by ippocratis** [comment]
[READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE)


"Starting in API level 33, this permission has no effect. If your app accesses other apps' media files, request one or more of these permissions instead: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, READ_MEDIA_AUDIO. L"


And to [Access other apps' media files](https://developer.android.com/training/data-storage/shared/media#access-other-apps-files) that other apps have created, you must declare the appropriate storage-related permissions, and the files must reside in one of the following media collections:

    MediaStore.Images
    MediaStore.Video
    MediaStore.Audio


Looked at the apps requested permissions 

`aapt dump xmltree  /sdcard/Download/uhuru.apk  AndroidManifest.xml`

Looks like 
READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, 

Permissions are not requested


May all this be relative? 

Sorry if I make no sense . I'm only hard guessing here.

**Comment by savvasdalkitsis** [comment]
The permission set of the app should work fine as the old android.permission.READ_EXTERNAL_STORAGE works fine still.

I believe the issue is that you have so many photos in your phone, and the app is scanning them in a random order, perhaps leaving the camera ones to be scanned much later. 

Have you seen the sync progress notification finishing? It should tell you the total number of media being scanned and how many have been scanned so far.

I also literally just made a change, which will be on the next release, that will prioritize the camera media (when found) to be scanned first so the UX is a bit better

**Comment by ippocratis** [comment]
Indeed
in the notification progress bar it States there are ~2500 files

Strange thing is 
I have ~250 photos in DCIM/Camera and another ~300 in /Pictures subfolders

The scan finishes just fine

**Comment by savvasdalkitsis** [comment]
The app scans ALL public local media in all folders that any app creates. things like whatsapp, telegram, photo editors etc all have their own folders that are published. Prioritizing the camera folder will make this process much nicer i think.

**Comment by ippocratis** [comment]
local photos photos & sync/local/remote icons appear as expected now.
V.0.084
Not sure what went wrong
