### ISSUE TITLE
Recently hidden photos do not show up

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#200]
When hiding new photos in the web app, these new photos are not showing in the hidden photos section of uhuru photos. Only previously hidden photos appear.

**Comment by nagarrido** [comment]
Any news on this? Not a critical function but it's still a bug

**Comment by savvasdalkitsis** [comment]
I will be looking to fix this for the public release

**Comment by savvasdalkitsis** [comment]
The next release should fix some bad behaviour around hidden photos. Please re-raise this if your issue is not fixed
