### ISSUE TITLE
V0.0.91-92 crashes when opening any media

### ISSUE THREAD

**Issue by ippocratis** [savvasdalkitsis/uhuruphotos-android#216]
Logcat reader
[logcat_04-22-2023_20-51-05.txt](https://github.com/savvasdalkitsis/uhuruphotos-android/files/11301992/logcat_04-22-2023_20-51-05.txt)

**Comment by ippocratis** [comment]
[log.log](https://github.com/savvasdalkitsis/uhuruphotos-android/files/11302004/log.log)

**Comment by ippocratis** [comment]
Uhuruphotos log
[log.log](https://github.com/savvasdalkitsis/uhuruphotos-android/files/11302005/log.log)

**Comment by ippocratis** [comment]
V0.0.92 still crassness the app opening any media

Uhuru logs
[log (2).log](https://github.com/savvasdalkitsis/uhuruphotos-android/files/11302314/log.2.log)

**Comment by savvasdalkitsis** [comment]
Should be fixed by https://github.com/savvasdalkitsis/uhuruphotos-android/releases/tag/v0.0.94
