### ISSUE TITLE
Synchronizing local media never ends

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#251]
Since the last release, every time I enter the app local media starts synchronizing. Once it finishes, if I leave the feed screen (for example, if I go to albums), and then I return to the feed section, local media starts synchronizing again. This causes the app to never stop synchronizing local media, and consumes a lot of battery. I can replicate this behaviour in more than one device.

**Comment by savvasdalkitsis** [comment]
Replicated. Will be fixed in the next release
