### ISSUE TITLE
Usage of deprecated endpoints

### ISSUE THREAD

**Issue by derneuere** [savvasdalkitsis/uhuruphotos-android#408]
I marked a while ago the endpoint `/api/photos/hidden/` and `/api/photos/favorite/` as deprecated and removed it in the dev branch a couple of commits ago. 

It looks like UhuruPhotos still depends on it https://github.com/savvasdalkitsis/uhuruphotos-android/blob/20df60b6db2686256430a5322c05442d493b20c3/feature/media/remote/domain/implementation/src/main/kotlin/com/savvasdalkitsis/uhuruphotos/feature/media/remote/domain/implementation/service/RemoteMediaService.kt#L57-L61

It is now a parameter `?favorite=true` and `?hidden=true` in `/api/albums/date/list/` and `/api/albums/date/{id}` similar to 
https://github.com/savvasdalkitsis/uhuruphotos-android/blob/20df60b6db2686256430a5322c05442d493b20c3/feature/trash/domain/implementation/src/main/kotlin/com/savvasdalkitsis/uhuruphotos/feature/trash/domain/implementation/service/TrashService.kt#L23-L31

If you don't have time to migrate, I can add the endpoints back, and we remove them in a later release.

**Comment by savvasdalkitsis** [comment]
ah thanks for the heads up. i will switch to the new endpoint for th next release
