### ISSUE TITLE
Issue with new permissions constraints on Android 14

### ISSUE THREAD

**Issue by robotfishe** [savvasdalkitsis/uhuruphotos-android#412]
Just installed the app on my Pixel Fold running the last Android 14 beta, and it's crashing on login and logging a permission issue:

`2023-08-15 21:39:08,074 ERROR [Parcel:3057 createExceptionOrNull]: java.lang.SecurityException: Starting FGS with type dataSync callerApp=ProcessRecord{aafca11 30351:com.savvasdalkitsis.uhuruphotos/u0a664} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] `

I tried to grant that permission manually through ADB, but Android won't let me, even as root.

I think this is probably related to Android 14's new requirements on foreground service type specifications: https://developer.android.com/about/versions/14/changes/fgs-types-required

**Comment by savvasdalkitsis** [comment]
I will try out on a 14 emulator and fix for the next release
