### ISSUE TITLE
Api 24 fixes

### ISSUE THREAD

**Issue by savvasdalkitsis** [savvasdalkitsis/uhuruphotos-android#445]
Some things are not working on the minimum supported api level.

Feed not loading
Missing column from local media db query

**Comment by c0bnut** [comment]
Would this be causing lag, stuttering in the app when browsing the feed and opening photos?

**Comment by savvasdalkitsis** [comment]
Download the latest version just publisedh @c0bnut (0.0.169) which should have fixed the slowness in the app. it was unrelated to this.

Let me know if that version solves your problems

**Comment by c0bnut** [comment]
Yes, the latest release appears to have resolved the performance issues, thank you.
