### ISSUE TITLE
 Allow remembering credentials on login page

### ISSUE THREAD

**Issue by savvasdalkitsis** [savvasdalkitsis/uhuruphotos-android#455]
related to https://github.com/LibrePhotos/librephotos/issues/924

**Comment by nagarrido** [comment]
This would be nice, it's really annoying that librephotos logs you out so often

**Comment by hardwareadictos** [comment]
Hey! Wanted to revive this issue because on Uhuru this doesn't work anymore, would be nice also to remember the login/keep the sesion logged on Android Web App 🙂
