### ISSUE TITLE
Some photos are never uploaded

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#463]
I'm having some problems with photos which are not being uploaded to the server. As a context, if it is relevant, I recently went into a trip in which I was offline, so I tried to sync over 100 photos once I connected to the Internet.

I sent you logs by email (same subject as this issue), in which I manually tried to sync one of the photos that doesn't want to be uploaded.

**Comment by savvasdalkitsis** [comment]
Duplicate of https://github.com/savvasdalkitsis/uhuruphotos-android/issues/454
