### ISSUE TITLE
More flexibility on sync and Download path

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#499]
It would be nice to chose the folders that are backed up, and the download folder when you Download an image.

This would problems such as my photos being in DCIM/Camera, but the photos being downloaded to DCIM, thus not appearing as downloaded in the app.

**Comment by savvasdalkitsis** [comment]
i could look into making the folder that the app downloads photos at condigureable but before i look into that, this is interesting. The app should be scanning the root DCIM folder anyway and it should see the photos downloaded and match them with the remote version on the server and show it to you as synced.

Can you see the downloaded photo in the library section of the app?

**Comment by nagarrido** [comment]
Yes, the DCIM folder appears in the library section once I download the photo, but does not appear as synced in the feed section. I remember that last year, in some release, the sync status displayed correctly but I do not know when it stopped working. (I can reproduce this behaviour in 2 devices)

**Comment by marcel89l** [comment]
I would also like to configure which folders on my Phone should be considered using the sync. Example:
- Till Last week i used a camera App which saved pictures to " /storage/emulated/0/DCIM/Camera/". This folder was correctly synced to my Server with UhuruPhotos
-  Then i changed my camera App, now pictures are stored under " /storage/emulated/0/DCIM/" directly. I can see those Pictures in uhuruphotos when i open the library, but they are noch synced to my Server
- this one is probably not intended to work that way, but i would like to manually sync pictures from my phone to my Server. I would like the solution that i manually choose those Pictures in the uhuruphotos library (for example
 /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Images/IMG-xyz.jpg) and have a option to sync this specific photo, but this is not possible...

**Comment by savvasdalkitsis** [comment]
The usecase of selecting multiple folders to contribute to the feed (and thus be synced to the server as well) is now fixed.

I will leave this issue open to address the last item in @marcel89l's last comment in a future update
