### ISSUE TITLE
Update Simplified Chinese (zh-Hans) translation

### ISSUE THREAD

**Issue by clsty** [savvasdalkitsis/uhuruphotos-android#513]
I just contributed for `zh-Hans`. Some of the entries need a reviewer to approve suggestions, but I saw another person's suggestion not approved nor rejected which was created months ago.

Please consider let me be a reviewer for zh-Hans. I have some experiences on English-to-Chinese translation.
Thank you.

**Comment by savvasdalkitsis** [comment]
So I just accepted all translations from weblate, but i saw this issue after i merged everything. I am not sure if yours or the other reviewer's translations made it in. 

Let me know if you feel the ones commited on `main` are not good and i will try to revert to an earlier commit using your translations

**Comment by clsty** [comment]
Actually I had submitted a PR which was merged hours ago, but again overwritten by the old version from weblate.

See https://github.com/savvasdalkitsis/uhuruphotos-android/pull/516

I hope you could revert to this commit. Thanks!

**Comment by savvasdalkitsis** [comment]
I believe this is now fixed. Close the PR if that's the case or let me know if i messed it up again so I can fix it :D

**Comment by clsty** [comment]
Yeah, it's fixed now. Thank you!
