### ISSUE TITLE
Is it possible to use advanced features without a server?

### ISSUE THREAD

**Issue by Rafee-M** [savvasdalkitsis/uhuruphotos-android#550]
It'd be really helpful if it was possible to run the advanced features locally on device

**Comment by savvasdalkitsis** [comment]
This is currently outside the scope of the app as it would require significant work.

Perhaps something for v2 of the app once I start adding other backends other than LibrePhotos (if I ever get around to it)

I am open to PRs though so if you want to contribute some of the features you are missing, feel free 😄
