### ISSUE TITLE
It always say connect to server is lost and need to retype account 

### ISSUE THREAD

**Issue by fofc12** [savvasdalkitsis/uhuruphotos-android#682]
i start a librephoto server in docker locally, uhuruphoto always say connect to server is lost and need to retype account every time regardless i check the"remember" option.

**Comment by CodingGhost** [comment]
I have the same problem, cant use the app like that.

**Comment by nagarrido** [comment]
Same. I love this app, but sadly until this is fixed I have to use the web app 😓
