### ISSUE TITLE
Allow full image resolution (feature request)

### ISSUE THREAD

**Issue by ippocratis** [savvasdalkitsis/uhuruphotos-android#88]
For now the only option to get a photo in full resolution is to share it with an app that you can download it.
It would make sense if there would be a way to get the full resolution e.g. when zooming it  or a way maybe to download it directly?

**Comment by savvasdalkitsis** [comment]
The app (unlike the web app) loads the full resolution for displaying. In terms of downloading it locally, you can do this via share to a file app but i guess i could add a dedicated download button too

**Comment by ippocratis** [comment]
Ok
I'm not sure what is going on
For some pics a get a share button on the image view window and for some I dont.
For the with a share button I actually get the full resolution and I canzoom all the way in without quality loss .for the others I dont .

**Comment by savvasdalkitsis** [comment]
The share button shows up when the full resolution finishes downloading for display.

Now it is possible that the image is of an unsupported type on android (RAW images won't display for instance by default) and I have a ticket to add some way to support those (display a higher resolution thumbnail like the web does and provide a separate download button perhaps)

https://github.com/savvasdalkitsis/uhuruphotos-android/issues/11

If the image you are seeing this on is a simple jpeg or png which should be working, either give it more time to download (maybe it's slow) or if there is an error maybe share some logs?

**Comment by ippocratis** [comment]
Simple jpg's
I have send you a pm

**Comment by savvasdalkitsis** [comment]
Closing as it turns out the full image cannot be downloaded from the web app either so it's a LibrePhotos issue
