### ISSUE TITLE
Photos gone from feed when refreshing albums

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#942]
When I enter a user created album and I refresh the photos, these photos dissappear from the main feed (timeline). Refreshing the timeline or a particular day brings the photos back, but of course the ideal scenario would be that this does nor happen at all

**Comment by savvasdalkitsis** [comment]
Hm i cannot replicate that. can you provide some logs maybe?

**Comment by nagarrido** [comment]
Just sent you the logs replicating the bug. I refreshed the album and then refreshed the feed. The issue should be happening for photos from today and yesterday

**Comment by savvasdalkitsis** [comment]
Hm not very useful logs. Does it happen for you every time you do this?

**Comment by nagarrido** [comment]
Yes, every time and on 2 different devices. Maybe I did not explain the steps to reproduce correctly:

1. Add recent photos to a user created album (maybe ones just taken, to make it easier)
2. Go to the album and refresh it, since the new photos will not be shown immediately if the album content was cached previously
3. Go to feed, and the photos disappear

Please let me know if this is more useful, or if it is my particular case

**Comment by savvasdalkitsis** [comment]
Can you try version 0.0.226 and see if that fixes it for you?

**Comment by nagarrido** [comment]
I can confirm this is fixed in the last version :)
