### ISSUE TITLE
Map dissappears for videos

### ISSUE THREAD

**Issue by nagarrido** [savvasdalkitsis/uhuruphotos-android#97]
When scrolling up in a video to see the metadata, the map box is transparent and part of the video is shown 

![Screenshot_20220715-021440_Photos.jpg](https://user-images.githubusercontent.com/37604199/179162781-45b44859-457e-4527-a3ab-2a504ecab81c.jpg)

**Comment by savvasdalkitsis** [comment]
Duplicate of https://github.com/savvasdalkitsis/uhuruphotos-android/issues/72

(note that this doesn't happen with Google Maps, only Mapbox seems to have this issue)
